<?php

namespace Database\Seeders;

use App\Models\SiteContent;
use Illuminate\Database\Seeder;

class SiteContentSeeder extends Seeder
{
    public function run(): void
    {
        $contents = [
            // Hero Section
            [
                'section' => 'hero',
                'key' => 'background',
                'type' => 'image',
                'value' => '/home_images/dashboard.png',
                'label' => 'Imagen de fondo',
                'order' => 1,
            ],
            [
                'section' => 'hero',
                'key' => 'paso_1',
                'type' => 'text',
                'value' => 'Ingrese el número de RUT/DNI/pasaporte del alumno',
                'label' => 'Paso 1 - Instrucción',
                'order' => 3,
            ],
            [
                'section' => 'hero',
                'key' => 'paso_2',
                'type' => 'text',
                'value' => 'Seleccione el programa a pagar',
                'label' => 'Paso 2 - Instrucción',
                'order' => 4,
            ],
            [
                'section' => 'hero',
                'key' => 'paso_3',
                'type' => 'text',
                'value' => 'Seleccione el método de pago y boleta',
                'label' => 'Paso 3 - Instrucción',
                'order' => 5,
            ],
            // Schools Section
            [
                'section' => 'schools',
                'key' => 'titulo',
                'type' => 'text',
                'value' => 'Colegios que nos acompañan',
                'label' => 'Título de la sección',
                'order' => 1,
            ],

            // Transform Section
            [
                'section' => 'transform',
                'key' => 'texto_linea_1',
                'type' => 'html',
                'value' => 'Transformamos cada <strong>experiencia</strong>',
                'label' => 'Primera línea de texto',
                'order' => 1,
            ],
            [
                'section' => 'transform',
                'key' => 'texto_linea_2',
                'type' => 'text',
                'value' => 'en un programa único, fomentando la conexión, respeto',
                'label' => 'Segunda línea de texto',
                'order' => 2,
            ],
            [
                'section' => 'transform',
                'key' => 'texto_linea_3',
                'type' => 'html',
                'value' => 'y la <strong>exploración</strong>.',
                'label' => 'Tercera línea de texto',
                'order' => 3,
            ],
            [
                'section' => 'transform',
                'key' => 'imagen_1',
                'type' => 'image',
                'value' => '/home_images/section_img1.png',
                'label' => 'Imagen decorativa 1',
                'order' => 4,
            ],
            [
                'section' => 'transform',
                'key' => 'imagen_2',
                'type' => 'image',
                'value' => '/home_images/section_img2.png',
                'label' => 'Imagen decorativa 2',
                'order' => 5,
            ],

            // Experiences Section
            [
                'section' => 'experiences',
                'key' => 'titulo',
                'type' => 'text',
                'value' => 'Nuestras experiencias',
                'label' => 'Título de la sección',
                'order' => 1,
            ],
            [
                'section' => 'experiences',
                'key' => 'tarjeta_1_titulo',
                'type' => 'text',
                'value' => 'Viajes de estudio.',
                'label' => 'Tarjeta 1 - Título',
                'order' => 2,
            ],
            [
                'section' => 'experiences',
                'key' => 'tarjeta_1_descripcion',
                'type' => 'textarea',
                'value' => 'Planificamos viajes de estudio en Chile y el extranjero, generando experiencias únicas de aprendizaje y entretención.',
                'label' => 'Tarjeta 1 - Descripción',
                'order' => 3,
            ],
            [
                'section' => 'experiences',
                'key' => 'tarjeta_1_imagen',
                'type' => 'image',
                'value' => '/images/banners/VIAJE_DE_ESTUDIO.webp',
                'label' => 'Tarjeta 1 - Imagen',
                'order' => 4,
            ],
            [
                'section' => 'experiences',
                'key' => 'tarjeta_2_titulo',
                'type' => 'text',
                'value' => 'Cursos de Educación al aire libre – CEAL.',
                'label' => 'Tarjeta 2 - Título',
                'order' => 5,
            ],
            [
                'section' => 'experiences',
                'key' => 'tarjeta_2_descripcion',
                'type' => 'textarea',
                'value' => 'Transformamos el medio natural en una gran sala de clases, con actividades educativas que fomenten el desarrollo de habilidades blandas y trabajo en equipo, junto a colegios y universidades.',
                'label' => 'Tarjeta 2 - Descripción',
                'order' => 6,
            ],
            [
                'section' => 'experiences',
                'key' => 'tarjeta_2_imagen',
                'type' => 'image',
                'value' => '/images/banners/CEAL.webp',
                'label' => 'Tarjeta 2 - Imagen',
                'order' => 7,
            ],
            [
                'section' => 'experiences',
                'key' => 'tarjeta_3_titulo',
                'type' => 'text',
                'value' => 'Giras Deportivas.',
                'label' => 'Tarjeta 3 - Título',
                'order' => 8,
            ],
            [
                'section' => 'experiences',
                'key' => 'tarjeta_3_descripcion',
                'type' => 'textarea',
                'value' => 'Ofrecemos un servicio integral que abarca desde la planificación personalizada hasta la asistencia en las salidas o viajes deportivos de tu colegio, universidad o club deportivo.',
                'label' => 'Tarjeta 3 - Descripción',
                'order' => 9,
            ],
            [
                'section' => 'experiences',
                'key' => 'tarjeta_3_imagen',
                'type' => 'image',
                'value' => '/images/banners/GIRAS_DEPORTIVAS.webp',
                'label' => 'Tarjeta 3 - Imagen',
                'order' => 10,
            ],
            [
                'section' => 'experiences',
                'key' => 'tarjeta_4_titulo',
                'type' => 'text',
                'value' => 'Experiencias a tu medida.',
                'label' => 'Tarjeta 4 - Título',
                'order' => 11,
            ],
            [
                'section' => 'experiences',
                'key' => 'tarjeta_4_descripcion',
                'type' => 'textarea',
                'value' => 'Diseñamos programas, eventos o talleres personalizados, según tus necesidades. Algunas experiencias son: Summer Camp, Día de la familia o Kermesse, Campamento \'Padre-Hijo\', entre otros.',
                'label' => 'Tarjeta 4 - Descripción',
                'order' => 12,
            ],
            [
                'section' => 'experiences',
                'key' => 'tarjeta_4_imagen',
                'type' => 'image',
                'value' => '/images/banners/OTRAS_EXPERIENCIAS.webp',
                'label' => 'Tarjeta 4 - Imagen',
                'order' => 13,
            ],

            // Courses/Banners Section
            [
                'section' => 'courses',
                'key' => 'banner_1_destino',
                'type' => 'text',
                'value' => 'Norte de Chile',
                'label' => 'Banner 1 - Destino',
                'order' => 1,
            ],
            [
                'section' => 'courses',
                'key' => 'banner_1_imagen',
                'type' => 'image',
                'value' => '/images/banners/NORTE_CHILE.webp',
                'label' => 'Banner 1 - Imagen',
                'order' => 2,
            ],
            [
                'section' => 'courses',
                'key' => 'banner_2_destino',
                'type' => 'text',
                'value' => 'Sur de Chile',
                'label' => 'Banner 2 - Destino',
                'order' => 3,
            ],
            [
                'section' => 'courses',
                'key' => 'banner_2_imagen',
                'type' => 'image',
                'value' => '/images/banners/SUR_DE_CHILE.webp',
                'label' => 'Banner 2 - Imagen',
                'order' => 4,
            ],
            [
                'section' => 'courses',
                'key' => 'banner_3_destino',
                'type' => 'text',
                'value' => 'Perú',
                'label' => 'Banner 3 - Destino',
                'order' => 5,
            ],
            [
                'section' => 'courses',
                'key' => 'banner_3_imagen',
                'type' => 'image',
                'value' => '/images/banners/PERÚ.webp',
                'label' => 'Banner 3 - Imagen',
                'order' => 6,
            ],
            [
                'section' => 'courses',
                'key' => 'banner_4_destino',
                'type' => 'text',
                'value' => 'Brasil',
                'label' => 'Banner 4 - Destino',
                'order' => 7,
            ],
            [
                'section' => 'courses',
                'key' => 'banner_4_imagen',
                'type' => 'image',
                'value' => '/images/banners/BRASIL.webp',
                'label' => 'Banner 4 - Imagen',
                'order' => 8,
            ],
            [
                'section' => 'courses',
                'key' => 'banner_5_destino',
                'type' => 'text',
                'value' => 'Estados Unidos',
                'label' => 'Banner 5 - Destino',
                'order' => 9,
            ],
            [
                'section' => 'courses',
                'key' => 'banner_5_imagen',
                'type' => 'image',
                'value' => '/images/banners/USA.webp',
                'label' => 'Banner 5 - Imagen',
                'order' => 10,
            ],
            [
                'section' => 'courses',
                'key' => 'banner_6_destino',
                'type' => 'text',
                'value' => 'Europa',
                'label' => 'Banner 6 - Destino',
                'order' => 11,
            ],
            [
                'section' => 'courses',
                'key' => 'banner_6_imagen',
                'type' => 'image',
                'value' => '/images/banners/EUROPA.webp',
                'label' => 'Banner 6 - Imagen',
                'order' => 12,
            ],
            [
                'section' => 'courses',
                'key' => 'banner_7_destino',
                'type' => 'text',
                'value' => 'Campamentos',
                'label' => 'Banner 7 - Destino',
                'order' => 13,
            ],
            [
                'section' => 'courses',
                'key' => 'banner_7_imagen',
                'type' => 'image',
                'value' => '/images/banners/CAMPAMENTOS.webp',
                'label' => 'Banner 7 - Imagen',
                'order' => 14,
            ],
            [
                'section' => 'courses',
                'key' => 'banner_8_destino',
                'type' => 'text',
                'value' => 'Centro de Desafíos Lat90',
                'label' => 'Banner 8 - Destino',
                'order' => 15,
            ],
            [
                'section' => 'courses',
                'key' => 'banner_8_imagen',
                'type' => 'image',
                'value' => '/images/banners/CEAL.webp',
                'label' => 'Banner 8 - Imagen',
                'order' => 16,
            ],
            [
                'section' => 'courses',
                'key' => 'boton_texto',
                'type' => 'text',
                'value' => 'Descubre más en nuestra web',
                'label' => 'Texto del botón CTA',
                'order' => 17,
            ],
            [
                'section' => 'courses',
                'key' => 'boton_url',
                'type' => 'text',
                'value' => 'https://www.latitud90.com',
                'label' => 'URL del botón CTA',
                'order' => 18,
            ],

            // FAQ Section
            [
                'section' => 'faq',
                'key' => 'titulo',
                'type' => 'text',
                'value' => 'Preguntas frecuentes',
                'label' => 'Título de la sección',
                'order' => 1,
            ],
            [
                'section' => 'faq',
                'key' => 'pregunta_1',
                'type' => 'text',
                'value' => '¿Cómo solicito el descuento de hermanos mellizos o gemelos?',
                'label' => 'Pregunta 1',
                'order' => 2,
            ],
            [
                'section' => 'faq',
                'key' => 'respuesta_1',
                'type' => 'textarea',
                'value' => 'A través de su ejecutivo comercial.',
                'label' => 'Respuesta 1',
                'order' => 3,
            ],
            [
                'section' => 'faq',
                'key' => 'pregunta_2',
                'type' => 'text',
                'value' => '¿Cómo activar las cuotas para el pago mensual con tarjeta de débito o transferencia electrónica a través de la tienda online?',
                'label' => 'Pregunta 2',
                'order' => 4,
            ],
            [
                'section' => 'faq',
                'key' => 'respuesta_2',
                'type' => 'textarea',
                'value' => 'En caso de elegir esta opción de pago debes escribir a pagos@latitud90.com.',
                'label' => 'Respuesta 2',
                'order' => 5,
            ],
            [
                'section' => 'faq',
                'key' => 'pregunta_3',
                'type' => 'text',
                'value' => '¿Cómo puedo confirmar que he pagado?',
                'label' => 'Pregunta 3',
                'order' => 6,
            ],
            [
                'section' => 'faq',
                'key' => 'respuesta_3',
                'type' => 'textarea',
                'value' => 'La confirmación es automática, a través de la recepción de la boleta a la dirección electrónica informada al momento del pago.',
                'label' => 'Respuesta 3',
                'order' => 7,
            ],
            [
                'section' => 'faq',
                'key' => 'pregunta_4',
                'type' => 'text',
                'value' => '¿En caso de no ser apoderado o representante legal puedo pagar?',
                'label' => 'Pregunta 4',
                'order' => 8,
            ],
            [
                'section' => 'faq',
                'key' => 'respuesta_4',
                'type' => 'textarea',
                'value' => 'Si puede hacerlo, siempre que conozca los datos del participante al cual pagara o abonara.',
                'label' => 'Respuesta 4',
                'order' => 9,
            ],
            [
                'section' => 'faq',
                'key' => 'pregunta_5',
                'type' => 'text',
                'value' => '¿Hasta cuándo tengo plazo para pagar el viaje de estudios?',
                'label' => 'Pregunta 5',
                'order' => 10,
            ],
            [
                'section' => 'faq',
                'key' => 'respuesta_5',
                'type' => 'textarea',
                'value' => 'La fecha límite para comenzar el pago está indicada en el documento "FORMAS DE PAGO".',
                'label' => 'Respuesta 5',
                'order' => 11,
            ],
            [
                'section' => 'faq',
                'key' => 'pregunta_6',
                'type' => 'text',
                'value' => '¿Qué pasa si la operación del pago con mi tarjeta de débito o transferencia Khipu es rechazada?',
                'label' => 'Pregunta 6',
                'order' => 12,
            ],
            [
                'section' => 'faq',
                'key' => 'respuesta_6',
                'type' => 'textarea',
                'value' => 'Verifique si el límite diario de su banco le permite pagar el monto que intenta abonar. Tenga presente que por tema de seguridad bancaria, el monto de la primera transferencia o pago estará limitada.',
                'label' => 'Respuesta 6',
                'order' => 13,
            ],

            // Program Detail - Warning Section
            [
                'section' => 'program_detail',
                'key' => 'titulo',
                'type' => 'text',
                'value' => 'El itinerario o programa puede sufrir modificaciones por razones de fuerza mayor',
                'label' => 'Advertencia - Título',
                'order' => 1,
            ],
            [
                'section' => 'program_detail',
                'key' => 'descripcion',
                'type' => 'textarea',
                'value' => 'Como condiciones meteorológicas, pandemia, normas sanitarias, cortes de puentes, pasos fronterizos, catástrofe o estado de excepción. Para más información, descarga ',
                'label' => 'Advertencia - Descripción',
                'order' => 2,
            ],
            [
                'section' => 'program_detail',
                'key' => 'texto_itinerario',
                'type' => 'text',
                'value' => ' el itinerario completo o consúltanos a nuestro correo eléctrico ',
                'label' => 'Advertencia - Texto itinerario',
                'order' => 3,
            ],
            [
                'section' => 'program_detail',
                'key' => 'email',
                'type' => 'text',
                'value' => 'educacion@latitud90.com',
                'label' => 'Advertencia - Email de contacto',
                'order' => 4,
            ],

            // Footer Section
            [
                'section' => 'footer',
                'key' => 'newsletter_titulo',
                'type' => 'text',
                'value' => 'Suscríbete a nuestro newsletter',
                'label' => 'Newsletter - Título',
                'order' => 1,
            ],
            [
                'section' => 'footer',
                'key' => 'newsletter_placeholder',
                'type' => 'text',
                'value' => 'Ingresa su email aqui.',
                'label' => 'Newsletter - Placeholder',
                'order' => 2,
            ],
            [
                'section' => 'footer',
                'key' => 'newsletter_boton',
                'type' => 'text',
                'value' => 'Subscribe',
                'label' => 'Newsletter - Botón',
                'order' => 3,
            ],
            [
                'section' => 'footer',
                'key' => 'email_contacto',
                'type' => 'text',
                'value' => 'educacion@latitud90.com',
                'label' => 'Email de contacto',
                'order' => 4,
            ],
            [
                'section' => 'footer',
                'key' => 'email_pagos',
                'type' => 'text',
                'value' => 'pagos@latitud90.com',
                'label' => 'Email para pagos',
                'order' => 5,
            ],
            [
                'section' => 'footer',
                'key' => 'direccion',
                'type' => 'text',
                'value' => 'Carlos Antúnez 1941, Providencia',
                'label' => 'Dirección',
                'order' => 6,
            ],
            [
                'section' => 'footer',
                'key' => 'facebook_url',
                'type' => 'text',
                'value' => 'https://www.facebook.com/latitud90',
                'label' => 'Facebook URL',
                'order' => 7,
            ],
            [
                'section' => 'footer',
                'key' => 'instagram_url',
                'type' => 'text',
                'value' => 'https://www.instagram.com/latitud90',
                'label' => 'Instagram URL',
                'order' => 8,
            ],
            [
                'section' => 'footer',
                'key' => 'linkedin_url',
                'type' => 'text',
                'value' => 'https://www.linkedin.com/company/latitud90',
                'label' => 'LinkedIn URL',
                'order' => 9,
            ],
            [
                'section' => 'footer',
                'key' => 'copyright',
                'type' => 'text',
                'value' => 'Copyright © 2025 Latitud90',
                'label' => 'Texto de copyright',
                'order' => 10,
            ],
            // Contact / WhatsApp Section
            [
                'section' => 'contact',
                'key' => 'whatsapp',
                'type' => 'text',
                'value' => '56988071858',
                'label' => 'Número de WhatsApp (sin +)',
                'order' => 1,
            ],
            [
                'section' => 'contact',
                'key' => 'whatsapp_mensaje',
                'type' => 'text',
                'value' => 'Hola, me gustaría obtener más información',
                'label' => 'Mensaje predeterminado de WhatsApp',
                'order' => 2,
            ],
        ];

        foreach ($contents as $content) {
            // Agregar default_value igual a value y use_default en true
            $content['default_value'] = $content['value'];
            $content['use_default'] = true;

            SiteContent::updateOrCreate(
                ['section' => $content['section'], 'key' => $content['key']],
                $content
            );
        }
    }
}
